apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: better-wellness-api-ingress
  namespace: better-wellness
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2  # Rewrite path to preserve the dynamic part
    nginx.ingress.kubernetes.io/affinity: "true"  # Optional: to ensure traffic is sticky to the same pod
spec:
  ingressClassName: nginx
  rules:
    - host: api.better-wellness.local  # Different subdomain for APIs
      http:
        paths:
          - path: /better-wellness/user
            pathType: Prefix
            backend:
              service:
                name: better-wellness-user-service
                port:
                  number: 80

          - path: /better-wellness/booking(/|$)(.*)
            pathType: ImplementationSpecific  # Use regular expressions to match dynamic paths
            backend:
              service:
                name: better-wellness-booking-service
                port:
                  number: 80

          - path: /api/chat
            pathType: Prefix
            backend:
              service:
                name: better-wellness-messaging-service
                port:
                  number: 80
