apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: better-wellness-ingress
  namespace: better-wellness
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  # Ensure class is specified (esp. for Minikube)
  rules:
    - host: better-wellness.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: better-wellness-web-app-service
                port:
                  number: 80

          - path: /better-wellness/user
            pathType: Prefix
            backend:
              service:
                name: better-wellness-user-service
                port:
                  number: 80

          - path: /better-wellness/booking
            pathType: Prefix
            backend:
              service:
                name: better-wellness-booking-service
                port:
                  number: 80

          - path: /api/chat
            pathType: Prefix
            backend:
              service:
                name: better-wellness-messaging-service
                port:
                  number: 80
