apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-service-config
  namespace: better-wellness
data:
  application.properties: |
    # Replace with your actual properties
    app.cors.allowed-origins=https://dev.*.amplifyapp.com
    spring.application.name=betterwellness
    server.port=8080
    management.endpoints.web.exposure.include=health
    management.endpoint.health.show-details=always

    spring.datasource.url=jdbc:mysql://mysql-service.default.svc.cluster.local:3306/betterwellness
    spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
    #spring.datasource.username=admin
    spring.datasource.username=root
    spring.datasource.password=root
    spring.jpa.hibernate.ddl-auto = update
    spring.jpa.show-sql=true