apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: better-wellness-booking-hpa
  namespace: better-wellness
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: better-wellness-booking-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
