apiVersion: apps/v1
kind: Deployment
metadata:
  name: better-wellness-web-app
  namespace: better-wellness
  labels:
    app: better-wellness-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: better-wellness-web-app
  template:
    metadata:
      labels:
        app: better-wellness-web-app
    spec:
      containers:
        - name: better-wellness-web-app-container
          image: 061039760516.dkr.ecr.ap-south-1.amazonaws.com/better-wellness-repo:better-wellness-webappv2
          ports:
            - containerPort: 80    # <- CHANGE here
      imagePullSecrets:
        - name: ecr-regcred
