apiVersion: v1
kind: Service
metadata:
  name: better-wellness-web-app-service
  namespace: better-wellness
spec:
  type: LoadBalancer
  selector:
    app: better-wellness-web-app
  ports:
    - port: 80
      targetPort: 80
