AWSTemplateFormatVersion: '2010-09-09'
Resources:

  BetterWellnessRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: BetterWellnessRestApi
      EndpointConfiguration:
        Types: [REGIONAL]

  ######################
  # USER ROUTES
  ######################

  UserResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ParentId: !GetAtt BetterWellnessRestApi.RootResourceId
      PathPart: user

  UserCustomerResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ParentId: !Ref UserResource
      PathPart: customer

  UserCustomerMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ResourceId: !Ref UserCustomerResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: HTTP
        IntegrationHttpMethod: ANY
        Uri: http://af226975787144e32a8c99ad7002e334-414598277.ap-south-1.elb.amazonaws.com/better-wellness/user/customer
        IntegrationResponses:
          - StatusCode: 200
        RequestTemplates:
          application/json: "{ \"statusCode\": 200 }"
      MethodResponses:
        - StatusCode: 200

  UserCustomerIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ParentId: !Ref UserCustomerResource
      PathPart: '{customerId}'

  UserCustomerIdMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ResourceId: !Ref UserCustomerIdResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: HTTP
        IntegrationHttpMethod: ANY
        Uri: http://af226975787144e32a8c99ad7002e334-414598277.ap-south-1.elb.amazonaws.com/better-wellness/user/customer/{customerId}
        IntegrationResponses:
          - StatusCode: 200
        RequestTemplates:
          application/json: "{ \"statusCode\": 200 }"
      MethodResponses:
        - StatusCode: 200

  UserCounselorResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ParentId: !Ref UserResource
      PathPart: counselor

  UserCounselorMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ResourceId: !Ref UserCounselorResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: HTTP
        IntegrationHttpMethod: ANY
        Uri: http://af226975787144e32a8c99ad7002e334-414598277.ap-south-1.elb.amazonaws.com/better-wellness/user/counselor
        IntegrationResponses:
          - StatusCode: 200
        RequestTemplates:
          application/json: "{ \"statusCode\": 200 }"
      MethodResponses:
        - StatusCode: 200

  UserCounselorIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ParentId: !Ref UserCounselorResource
      PathPart: '{counselorId}'

  UserCounselorIdMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ResourceId: !Ref UserCounselorIdResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: HTTP
        IntegrationHttpMethod: ANY
        Uri: http://af226975787144e32a8c99ad7002e334-414598277.ap-south-1.elb.amazonaws.com/better-wellness/user/counselor/{counselorId}
        IntegrationResponses:
          - StatusCode: 200
        RequestTemplates:
          application/json: "{ \"statusCode\": 200 }"
      MethodResponses:
        - StatusCode: 200

  ######################
  # BOOKING ROUTES
  ######################

  BookingResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ParentId: !GetAtt BetterWellnessRestApi.RootResourceId
      PathPart: booking

  AppointmentResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ParentId: !Ref BookingResource
      PathPart: appointment

  AppointmentMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ResourceId: !Ref AppointmentResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: HTTP
        IntegrationHttpMethod: ANY
        Uri: http://a9de8c37cbcda4090a5de1cd7cd4905d-388575420.ap-south-1.elb.amazonaws.com/better-wellness/booking/appointment
        IntegrationResponses:
          - StatusCode: 200
        RequestTemplates:
          application/json: "{ \"statusCode\": 200 }"
      MethodResponses:
        - StatusCode: 200

  AvailabilityResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ParentId: !Ref BookingResource
      PathPart: availability

  AvailabilityMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ResourceId: !Ref AvailabilityResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: HTTP
        IntegrationHttpMethod: ANY
        Uri: http://a9de8c37cbcda4090a5de1cd7cd4905d-388575420.ap-south-1.elb.amazonaws.com/better-wellness/booking/availability
        IntegrationResponses:
          - StatusCode: 200
        RequestTemplates:
          application/json: "{ \"statusCode\": 200 }"
      MethodResponses:
        - StatusCode: 200

  ######################
  # CHAT ROUTES
  ######################

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ParentId: !GetAtt BetterWellnessRestApi.RootResourceId
      PathPart: api

  ChatResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ParentId: !Ref ApiResource
      PathPart: chat

  ChatMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BetterWellnessRestApi
      ResourceId: !Ref ChatResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: HTTP
        IntegrationHttpMethod: ANY
        Uri: http://a8ebb8d2b454345db8d71828a361c0cf-1913399456.ap-south-1.elb.amazonaws.com/api/chat/history
        IntegrationResponses:
          - StatusCode: 200
        RequestTemplates:
          application/json: "{ \"statusCode\": 200 }"
      MethodResponses:
        - StatusCode: 200

  ######################
  # DEPLOYMENT & STAGE
  ######################

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - UserCustomerMethod
      - UserCustomerIdMethod
      - UserCounselorMethod
      - UserCounselorIdMethod
      - AppointmentMethod
      - AvailabilityMethod
      - ChatMethod
    Properties:
      RestApiId: !Ref BetterWellnessRestApi

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: prod
      RestApiId: !Ref BetterWellnessRestApi
      DeploymentId: !Ref ApiDeployment