AWSTemplateFormatVersion: '2010-09-09'
Resources:

  BetterWellnessHttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: BetterWellnessApi
      ProtocolType: HTTP

  # --- Integrations ---
  UserServiceIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      IntegrationType: HTTP_PROXY
      IntegrationUri: http://af226975787144e32a8c99ad7002e334-414598277.ap-south-1.elb.amazonaws.com/better-wellness/user
      IntegrationMethod: ANY
      PayloadFormatVersion: '1.0'

  BookingServiceIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      IntegrationType: HTTP_PROXY
      IntegrationUri: http://a9de8c37cbcda4090a5de1cd7cd4905d-388575420.ap-south-1.elb.amazonaws.com/better-wellness/booking
      IntegrationMethod: ANY
      PayloadFormatVersion: '1.0'

  ChatServiceIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      IntegrationType: HTTP_PROXY
      IntegrationUri: http://a8ebb8d2b454345db8d71828a361c0cf-1913399456.ap-south-1.elb.amazonaws.com/api/chat/history
      IntegrationMethod: ANY
      PayloadFormatVersion: '1.0'

  # --- User Routes ---
  RouteUserCustomer:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      RouteKey: ANY /user/customer
      Target: !Join [ "/", [ "integrations", !Ref UserServiceIntegration ] ]

  RouteUserCustomerId:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      RouteKey: ANY /user/customer/{customerId}
      Target: !Join [ "/", [ "integrations", !Ref UserServiceIntegration ] ]

  RouteUserCounselor:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      RouteKey: ANY /user/counselor
      Target: !Join [ "/", [ "integrations", !Ref UserServiceIntegration ] ]

  RouteUserCounselorId:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      RouteKey: ANY /user/counselor/{counselorId}
      Target: !Join [ "/", [ "integrations", !Ref UserServiceIntegration ] ]

  # --- Booking Routes ---
  RouteBookingAppointment:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      RouteKey: ANY /booking/appointment
      Target: !Join [ "/", [ "integrations", !Ref BookingServiceIntegration ] ]

  RouteBookingAppointmentProxy:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      RouteKey: ANY /booking/appointment/{proxy+}
      Target: !Join [ "/", [ "integrations", !Ref BookingServiceIntegration ] ]

  RouteBookingAvailability:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      RouteKey: ANY /booking/availability
      Target: !Join [ "/", [ "integrations", !Ref BookingServiceIntegration ] ]

  RouteBookingAvailabilityProxy:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      RouteKey: ANY /booking/availability/{proxy+}
      Target: !Join [ "/", [ "integrations", !Ref BookingServiceIntegration ] ]

  # --- Chat Routes ---
  RouteApiChatRoot:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      RouteKey: ANY /api/chat
      Target: !Join [ "/", [ "integrations", !Ref ChatServiceIntegration ] ]

  RouteApiChatProxy:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      RouteKey: ANY /api/chat/{proxy+}
      Target: !Join [ "/", [ "integrations", !Ref ChatServiceIntegration ] ]

  # --- Stage ---
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      StageName: $default
      AutoDeploy: true
