AWSTemplateFormatVersion: '2010-09-09'
Resources:

  BetterWellnessHttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: BetterWellnessApi
      ProtocolType: HTTP

  # --- Integrations ---
  UserServiceIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      IntegrationType: HTTP_PROXY
      IntegrationUri: http://af226975787144e32a8c99ad7002e334-414598277.ap-south-1.elb.amazonaws.com/user-service/{proxy}
      IntegrationMethod: ANY
      PayloadFormatVersion: '1.0'

  AppointmentServiceIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      IntegrationType: HTTP_PROXY
      IntegrationUri: http://a9de8c37cbcda4090a5de1cd7cd4905d-388575420.ap-south-1.elb.amazonaws.com/appointment-service/{proxy}
      IntegrationMethod: ANY
      PayloadFormatVersion: '1.0'

  MessagingServiceIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      IntegrationType: HTTP_PROXY
      IntegrationUri: http://a8ebb8d2b454345db8d71828a361c0cf-1913399456.ap-south-1.elb.amazonaws.com/messaging-service/{proxy}
      IntegrationMethod: ANY
      PayloadFormatVersion: '1.0'

  # --- Proxy Routes ----
  RouteUserServiceProxy:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      RouteKey: ANY /user-service/{proxy+}
      Target: !Join ["/", ["integrations", !Ref UserServiceIntegration]]

  RouteAppointmentServiceProxy:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      RouteKey: ANY /appointment-service/{proxy+}
      Target: !Join ["/", ["integrations", !Ref AppointmentServiceIntegration]]

  RouteMessagingServiceProxy:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      RouteKey: ANY /messaging-service/{proxy+}
      Target: !Join ["/", ["integrations", !Ref MessagingServiceIntegration]]

  # --- Stage ---
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref BetterWellnessHttpApi
      StageName: $default
      AutoDeploy: true