apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-service-config
  namespace: better-wellness
data:
  application.properties: |
    # Replace with your actual properties
    app.cors.allowed-origins=https://dev.*.amplifyapp.com
    spring.application.name=betterwellness
    server.port=8080
    chat.history.ttl=604800

    spring.datasource.url=jdbc:mysql://mysql-service.default.svc.cluster.local:3306/betterwellness
    spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
    #spring.datasource.username=admin
    spring.datasource.username=root
    spring.datasource.password=root
    spring.jpa.hibernate.ddl-auto = update
    spring.jpa.show-sql=true

    #spring.redis.host=localhost
    spring.redis.host=redis-service.default.svc.cluster.local
    spring.redis.port=6379
    spring.redis.password=
    spring.redis.ssl=false
