apiVersion: apps/v1
kind: Deployment
metadata:
  name: better-wellness-messaging-deployment
  namespace: better-wellness
  labels:
    app: better-wellness-messaging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: better-wellness-messaging-service
  template:
    metadata:
      labels:
        app: better-wellness-messaging-service
    spec:
      containers:
        - name: better-wellness-messaging-container
          image: 061039760516.dkr.ecr.ap-south-1.amazonaws.com//better-wellness-repo:better-wellness-messaging-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: config-volume
              mountPath: /app/application.properties
              subPath: application.properties
      volumes:
        - name: config-volume
          configMap:
            name: user-service-config   
      imagePullSecrets:
        - name: ecr-regcred
