apiVersion: v1
kind: Service
metadata:
  name: better-wellness-messaging-service
  namespace: better-wellness
spec:
  type: LoadBalancer
  selector:
    app: better-wellness-messaging-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080